
# https://aka.ms/yaml

name: $(BuildID)

trigger:
- main

variables:
  Configuration: Release
  BootsVersion: 1.0.4
  BootsSuffix: ''
  PackageVersion: $(BootsVersion).$(Build.BuildNumber)$(BootsSuffix)
  XA.Version: 11.3
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

- job: windows
  pool:
    vmImage: windows-latest
    demands: msbuild
  steps:

  - template: scripts/build-and-test.yaml
    parameters:
      platform: windows
      xamarinAndroidUrl: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4842306/main/bf63c3d116b38459678cb3aefd2f5826e78c385e/signed/Xamarin.Android.Sdk-11.3.99.57.vsix

  - powershell: dotnet cake
    displayName: Cake test
    workingDirectory: Cake.Boots

- job: mac
  pool:
    vmImage: macOS-latest
    demands: msbuild
  steps:

  - template: scripts/build-and-test.yaml
    parameters:
      platform: mac
      xamarinAndroidUrl: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4842306/main/bf63c3d116b38459678cb3aefd2f5826e78c385e/xamarin.android-11.3.99.57.pkg

  - bash: dotnet cake --target=Mono && dotnet cake
    workingDirectory: Cake.Boots
    displayName: Cake test
